server:
  port: 10102
spring:
  profiles:
    active: local
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${drug.datasource.driver-class-name}
    url: jdbc:mysql://${drug.datasource.host}:${drug.datasource.port}/${drug.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${drug.datasource.username}
    password: ${drug.datasource.password}
  data:
    redis:
      host: ${drug.redis.host}
      port: ${drug.redis.port}
      password: ${drug.redis.password}
      database: ${drug.redis.database}
  mail:
    host: ${drug.mail.host}
    username: ${drug.mail.username}
    password: ${drug.mail.password}
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: true
        debug: true
logging:
  file:
    name: src/main/resources/templates/logs.log
  level:
    com:
      supply:
        mapper: debug
        service: info
        controller: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.supply.entity
  configuration:
    map-underscore-to-camel-case: true
drug:
  jwt:
    secretKey: drugSupply
    ttl: 1209600000
    tokenName: token
  alioss:
    endpoint: ${drug.alioss.endpoint}
    access-key-id: ${drug.alioss.access-key-id}
    access-key-secret: ${drug.alioss.access-key-secret}
    bucket-name: ${drug.alioss.bucket-name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '药品供应链系统项目接口文档'
      paths-to-match: '/**'
      packages-to-scan: com.supply.controller